spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/dongly_dev}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      keepalive-time: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    com.dongly: DEBUG
    org.springframework.security: DEBUG
