spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      keepalive-time: 30000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    com.dongly: INFO
    org.springframework.web: WARN
